In [17]:
import numpy as np

sample = np.arange(16).reshape(2,2,4) #(0,1,2) 차원
print(sample)
print(sample.shape)
print(sample.ndim) 
print(sample.dtype.name)
print(sample.itemsize)
print(sample.size)
print(type(sample))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)
3
int32
4
16
<class 'numpy.ndarray'>


In [29]:
sample = np.arange(120).reshape(2,3,4,5) 
print(sample,end='\n\n')
print(sample.T) # (5,4,3,2)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]

[[[[  0  60]
   [ 20  80]
   [ 40 100]]

  [[  5  65]
   [ 25  85]
   [ 45 105]]

  [[ 10  70]
   [ 30  90]
   [ 50 110]]

  [[ 15  75]
   [ 35  95]
   [ 55 115]]]


 [[[  1  61]
   [ 21  81]
   [ 41 101]]

  [[  6  66]
   [ 26  86]
   [ 46 106]]

  [[ 11  71]
   [ 31  91]
   [ 51 111]]

  [[ 16  76]
   [ 36  96]
   [ 56 116]]]


 [[[  2  62]
   [ 22  82]
   [ 42 102]]

  [[  7  67

In [32]:
c = np.linspace(0,1,6)
d = np.linspace(0,1,5,endpoint=False)
print(c)
print(d)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


In [48]:
a = np.array([20,30,40,50])
b = np.arange(1,5)
a-b
print(a@b) # 내적. 같은 인덱스에 있는 요소들의 곱들의 합
sample1 = np.arange(6).reshape(2,3) #(0,1,2) 차원
sample2 = np.array([[10,20],[30,40],[50,60]])
# print(sample1)
# print(sample2)
# print(sample2-sample1)
print(sample1@sample2) # 행렬계산 * 차원 중요

400
[[130 160]
 [400 520]]
