# Homework 2 Prob 6.

***Double Click here to edit this cell***

- Name: 김현동
- Student ID: 201901208
- Submission date: 2023-04-12

# You must run this homework code on Google Colab

- DON'T run on Google Colab Pro
- DON'T use GPU or TPU

## Remark. If any kind of loops including for-loop, while-loops, list comprehension, and other loops are found, you get no points (0점).

## Use numpy wherever it is possible.


## Total: 30 pts

### You must run the following two cells to make sure you are running on Google Colab

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
addres

In [ ]:
!cat /proc/meminfo

MemTotal:       13297184 kB
MemFree:         8389152 kB
MemAvailable:   12405692 kB
Buffers:          327300 kB
Cached:          3839944 kB
SwapCached:            0 kB
Active:           597392 kB
Inactive:        4074500 kB
Active(anon):       1136 kB
Inactive(anon):   484148 kB
Active(file):     596256 kB
Inactive(file):  3590352 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               948 kB
Writeback:             0 kB
AnonPages:        504532 kB
Mapped:           251688 kB
Shmem:              1432 kB
KReclaimable:     143020 kB
Slab:             174052 kB
SReclaimable:     143020 kB
SUnreclaim:        31032 kB
KernelStack:        4176 kB
PageTables:         6924 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6648592 kB
Committed_AS:    2578576 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9044 kB
VmallocChunk:          0 kB
Percpu:          

## Problem 6 (20 pts)

- **find_k_nearest_index_big** returns the index of the k-nearest for 50 million data
- We want to time the execution
- *Do not use sklearn, scipy or any module computing k-nearest points directly*
- Use numpy functions only

In [ ]:
# import part here
import numpy as np

def find_k_nearest_index(data, center, k=1):

# YOUR CODE MUST BE HERE
    distances = np.sqrt(np.sum((data-center)**2,axis=1))

    nearest_index = np.argpartition(distances, k)[:k]
    nearest = np.where(distances <= np.max(distances[nearest_index]))[0]
    return np.sort(nearest)
def find_k_nearest_index_big(data, center, k=1):

# YOUR CODE MUST BE HERE
    block_size = 100000
    num_blocks = len(data) // block_size
    blocks = np.array_split(data, num_blocks)

    nearest_blocks = np.array(list(map(lambda x: find_k_nearest_index(x,center,k),blocks)))
    nearest_blocks = np.concatenate(nearest_blocks) + np.repeat(np.arange(num_blocks) * block_size, k)
    distances = np.sqrt(np.sum((data[nearest_blocks] - center) ** 2, axis=1))
    nearest = nearest_blocks[np.argpartition(distances, k)[:k]]
    return np.sort(nearest)






In [ ]:
# DO NOT EDIT THIS CELL

import time

np.random.seed(100)
data = np.random.randn(30000000,20)   # 30 million data
k = 5
center = np.random.randn(20)
start = time.time()
print(find_k_nearest_index_big(data, center, k))
end = time.time()

lapse = end - start
total = 10
weight = 1.5
grace = 20
my_point = int(total / (weight ** (lapse // grace)))
print(f'Total time taken : {lapse} seconds')
print(f'My point is {my_point}')

[ 5594529  9743426 16101792 17966020 26121068]
Total time taken : 3.3194377422332764 seconds
My point is 10


**Your time must be around:**
```
[ _____________________________________________ ]
Total time taken : 5.2564404010772705 seconds
My point is 10
```

In [ ]:
# DO NOT EDIT THIS CELL

import time

np.random.seed(100)
data = np.random.randn(50000000,20)   # 50 million data
k = 5
center = np.random.randn(20)
start = time.time()
print(find_k_nearest_index_big(data, center, k))
end = time.time()

lapse = end - start
total = 10
weight = 1.5
grace = 20
my_point = int(total / (weight ** (lapse // grace)))
print(f'Total time taken : {lapse} seconds')
print(f'My point is {my_point}')

[ 7095946 12357774 16298750 17671994 37962997]
Total time taken : 6.052914619445801 seconds
My point is 10


**Your time must be around:**
```
[ _____________________________________________ ]
Total time taken : 9.744923830032349 seconds
My point is 10
```

In [ ]:
# DO NOT EDIT THIS CELL

import time

np.random.seed(100)
data = np.random.randn(70000000,20)   # 70 million data
k = 5
center = np.random.randn(20)
start = time.time()
print(find_k_nearest_index_big(data, center, k))
end = time.time()

lapse = end - start
total = 10
weight = 1.5
grace = 40
my_point = int(total / (weight ** (lapse // grace)))
print(f'Total time taken : {lapse} seconds')
print(f'My point is {my_point}')

[ 8625157 10575612 24493637 47297630 67932745]
Total time taken : 14.391960144042969 seconds
My point is 10


**Your time must be around:**
```
[ _____________________________________________ ]
Total time taken : 20.60638999938965 seconds
My point is 10
```

## Ethics:
If you cheat, you will get negatgive of the total points.
If the homework total is 22 and you cheat, you get -22.

## What to submit

- Run **all cells** after restarting the kernel
- Goto "File -> Print Preview"
- Print the page as pdf
- Submit the pdf file in google classroom
- Pdf file name must be in a form of: homework_2_prob6_홍길동_202300001.pdf
- No late homeworks will be accepted
- Your homework will be graded on the basis of correctness, performance, and programming skills