# Numpy

## Tip

1. 모델에 넣을 학습 데이터 형태는 Numpy로 변환 -> 추론 결과 형태도 동일
- 물리적 공간 : 메모리 저장 방식의 차이 : list는 저장 주소가 확산되어 있음.
2. axis (축) : 다차원 배열에서 연산 기준 설정 요
3. numpy data type은 내부 값 변경시 새로운 객체를 반환함.
- list는 같은 pointer(위치)의 값만 변경해서 반환하지만 numpy는 새로운 pointer 생성

In [10]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## 파이썬 리스트와 처리 속도 비교

In [3]:
import random

my_arr = [random.random() for i in range(1_000_000)]

list

In [4]:
%%timeit

import statistics 

statistics.mean(my_arr)

723 ms ± 51.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%%timeit

np.mean(my_arr)

41.1 ms ± 4.57 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
np_arr = np.array(my_arr)

In [8]:
%%timeit

np.mean(np_arr)

1.12 ms ± 351 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

arr.shape


(2, 5)

In [19]:
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(len(arr))
print(arr.sort())

2
int32
10
2
None


## 생성

In [22]:
np.zeros((2,4))
np.ones((4,3))
arr = np.full((2,3),-1)
# same two types
np.zeros_like(arr)
np.zeros(arr.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

## indexing , slicing

In [26]:
print(arr[2:])
# print(arr[2])
print(arr[1,2])

[]
-1


### Boolean indexing

In [27]:
arr = np.array([1,2,3,4,5])

idx = np.array([False,True,True,False,True])

arr[idx]

array([2, 3, 5])

In [28]:
# ex) 3보다 큰 값만 가져오고 싶다
arr[arr>3] 

array([4, 5])

### Fancy indexing

In [29]:
idx = np.array([1,3])

arr[idx]

array([2, 4])

### 형태 변환

In [35]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
arr1 = arr.reshape(2,3)
arr2 = arr.reshape(6) # = arr.reshape(-1)
arr3 = arr.flatten()
print(arr1)
print(arr2)
print(arr3)
print(arr.reshape(1,2,3))
print(arr.reshape(1,-1,1))

(6,)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[[1 2 3]
  [4 5 6]]]
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]


In [46]:
print(arr)
arr[np.newaxis,np.newaxis]


[1 2 3 4 5 6]


array([[[1, 2, 3, 4, 5, 6]]])

# 데이터 저장 및 불러오기

In [49]:
np.savez('my_data.npz',train=arr)

In [50]:
load_arr = np.load('my_data.npz')

NpzFile 'my_data.npz' with keys: train


In [51]:
load_arr['train']

array([1, 2, 3, 4, 5, 6])