# plt.axis() 범위 지정 
 
 argument - x.min , x.max , y.min , y.max 
 
# 


In [1]:
import numpy as np


#np.float np.int
oneDim = np.array([1.0,2,3,4,5])
print(oneDIm)
print("Dimensinos=", oneDim.ndim) #몇 차원 배열?
print("Dimension=",oneDim.shape) # 몇 * 몇? tuple 출력
print("s")

NameError: name 'oneDIm' is not defined

In [ ]:
print(np.logspace(-3,3,7)) ## multiple이 같1다. log(x1)-log

In [ ]:
x=np.arange(-5,5)


y = x[3:5] #python에서는 copy하지만 np는 pinter
print(y)
y[:] = 1000
print(y)
print(x)


In [ ]:
#In[14]



### integer array indexing

univercial function???

In [ ]:
### sorting

t= np.random.randint(10,size=12).reshape(3,4)
print(t)
print()

print(np.sort(t))
print()
print(np.sort(t, axis=0)) ###### axis 축 y축 0 x축 1 z축 2

In [2]:
import numpy as np
import pandas as pd

### inplace 하게 저장됌. = memery에 저장됌.
a[:] =

### inplace 하지 않음. memry에 저장이 안됌. == 연산자 결과 false 
a = 

In [3]:

M = np.arange(25).reshape(5,5)
print(M)
print(M[M%2==1])
print(np.argwhere(M>=20))  #print index
print(np.where(M%2==1,M,0))   #홀수 값은 원래 값 짝수 값은 0 출력

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


In [4]:
import numpy as np
arr = np.array([1, -2, 3, -4, 5])
idx = np.where(arr > 0)[0]

print(idx)

[0 2 4]


###New axic

shape이 다를 때 연산. 일반적으로 연산이 안될거같음.

그런데 가능함. broad casting memory를 차지하지 않음. copy가 아님.

np.newaxs는 1로 치환. In[29]




In [5]:
a = np.array([[1],[2],[3]])
b = a.T
b + a


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [1]:
arr = [
    [1, 'Bread'],
    [2, 'Scandinavian'],
    [2, 'Scandinavian'],
    [3, 'Hot chocolate'],
    [3, 'Jam'],
    [3, 'Cookies'],
    [4, 'Muffin'],
    [5, 'Coffee'],
    [5, 'Pastry'],
    [5, 'Bread']
]

# 중복값 제거를 위해 set을 사용하여 중복을 제거한 key값의 리스트 생성
keys = list(set([sublist[0] for sublist in arr]))

# key를 key로, 중복 제거한 value 리스트를 value로 갖는 딕셔너리 생성
result_dict = {key: list(set([sublist[1] for sublist in arr if sublist[0] == key])) for key in keys}

print(result_dict)


{1: ['Bread'], 2: ['Scandinavian'], 3: ['Jam', 'Cookies', 'Hot chocolate'], 4: ['Muffin'], 5: ['Bread', 'Pastry', 'Coffee']}


In [10]:
import numpy as np

x = np.array(range(20)).reshape(10,2)

x - np.mean(x, axis=0)

array([[-9., -9.],
       [-7., -7.],
       [-5., -5.],
       [-3., -3.],
       [-1., -1.],
       [ 1.,  1.],
       [ 3.,  3.],
       [ 5.,  5.],
       [ 7.,  7.],
       [ 9.,  9.]])

In [ ]:
x = np.array(range(20)).reshape(10,2)

In [11]:
# scale 차이에 따른 점수 변환 
(x - x.mean(axis=0,keepdims=True))/x.std(axis=0,keepdims=True) *10 + 50

#표준편차 0~1 

array([[-9., -9.],
       [-7., -7.],
       [-5., -5.],
       [-3., -3.],
       [-1., -1.],
       [ 1.,  1.],
       [ 3.,  3.],
       [ 5.,  5.],
       [ 7.,  7.],
       [ 9.,  9.]])

In [22]:
#argsort vs sort

x = np.array([4,10,1,3,5,1,8])

print('sorted = \n', np.sort(x))
print('argsorted = \n', np.argsort(x)) ## index 출력 
print('partitioned \n', np.partition(x,3)) #sort는 아니지만 작은거 n개와 나머지



sorted = 
 [ 1  1  3  4  5  8 10]
argsorted = 
 [2 5 3 0 4 6 1]
partitioned 
 [ 1  3  1  4  5 10  8]


In [27]:
t = np.array([[1,2],[3,4],[5,6]])
np.sum(t, axis=1)

array([ 3,  7, 11])